name: USD News Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  usd-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests pillow

      - name: Run USD News Bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python usd_news.py

      - name: Save sent USD events
        run: |
          git config user.name "Forex News Bot"
          git config user.email "bot@github.com"

          git add sent_usd_events.json

          git diff --cached --quiet || git commit -m "Update sent USD events"

          git push
