name: Forex News Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  forex-news:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests pillow

      - name: Run Forex News Bot
        run: |
          python forex_news.py

      - name: Save sent news
        run: |
          git config user.name "Forex News Bot"
          git config user.email "bot@github.com"
          git add -A
          git commit -m "Update sent news" || exit 0
          git push
